### YamlMime:ManagedReference
items:
- uid: ASE_Assignment_Test.GlobalConfigTest
  commentId: T:ASE_Assignment_Test.GlobalConfigTest
  id: GlobalConfigTest
  parent: ASE_Assignment_Test
  children:
  - ASE_Assignment_Test.GlobalConfigTest.TestSetAndGetIsFillEnabled
  - ASE_Assignment_Test.GlobalConfigTest.TestSetAndGetMaxX
  - ASE_Assignment_Test.GlobalConfigTest.TestSetAndGetMaxY
  - ASE_Assignment_Test.GlobalConfigTest.TestSetAndGetPenSize
  - ASE_Assignment_Test.GlobalConfigTest.canvas
  langs:
  - csharp
  - vb
  name: GlobalConfigTest
  nameWithType: GlobalConfigTest
  fullName: ASE_Assignment_Test.GlobalConfigTest
  type: Class
  source:
    remote:
      path: ASE_Assignment_Test/GlobalConfigTest.cs
      branch: main
      repo: https://github.com/ASE-Classroom/ase-demo-assignment-Prapti-Acharya.git
    id: GlobalConfigTest
    path: ASE_Assignment_Test/GlobalConfigTest.cs
    startLine: 17
  assemblies:
  - ASE_Assignment_Test
  namespace: ASE_Assignment_Test
  summary: >-
    This test class validates the functionality of the GlobalConfig class.

    It ensures that the properties of GlobalConfig can be correctly set and retrieved.
  example: []
  syntax:
    content: >-
      [TestClass]

      public class GlobalConfigTest
    content.vb: >-
      <TestClass>

      Public Class GlobalConfigTest
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  attributes:
  - type: Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute
    ctor: Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute.#ctor
    arguments: []
- uid: ASE_Assignment_Test.GlobalConfigTest.canvas
  commentId: F:ASE_Assignment_Test.GlobalConfigTest.canvas
  id: canvas
  parent: ASE_Assignment_Test.GlobalConfigTest
  langs:
  - csharp
  - vb
  name: canvas
  nameWithType: GlobalConfigTest.canvas
  fullName: ASE_Assignment_Test.GlobalConfigTest.canvas
  type: Field
  source:
    remote:
      path: ASE_Assignment_Test/GlobalConfigTest.cs
      branch: main
      repo: https://github.com/ASE-Classroom/ase-demo-assignment-Prapti-Acharya.git
    id: canvas
    path: ASE_Assignment_Test/GlobalConfigTest.cs
    startLine: 23
  assemblies:
  - ASE_Assignment_Test
  namespace: ASE_Assignment_Test
  summary: Represents a canvas object to be used in tests.
  example: []
  syntax:
    content: public MyCanvas canvas
    return:
      type: ASE_Assignment_Prapti_Acharya_77356684.MyAppCanvas.MyCanvas
    content.vb: Public canvas As MyCanvas
- uid: ASE_Assignment_Test.GlobalConfigTest.TestSetAndGetMaxX
  commentId: M:ASE_Assignment_Test.GlobalConfigTest.TestSetAndGetMaxX
  id: TestSetAndGetMaxX
  parent: ASE_Assignment_Test.GlobalConfigTest
  langs:
  - csharp
  - vb
  name: TestSetAndGetMaxX()
  nameWithType: GlobalConfigTest.TestSetAndGetMaxX()
  fullName: ASE_Assignment_Test.GlobalConfigTest.TestSetAndGetMaxX()
  type: Method
  source:
    remote:
      path: ASE_Assignment_Test/GlobalConfigTest.cs
      branch: main
      repo: https://github.com/ASE-Classroom/ase-demo-assignment-Prapti-Acharya.git
    id: TestSetAndGetMaxX
    path: ASE_Assignment_Test/GlobalConfigTest.cs
    startLine: 28
  assemblies:
  - ASE_Assignment_Test
  namespace: ASE_Assignment_Test
  summary: Tests setting and getting the MaxX property of the GlobalConfig class.
  example: []
  syntax:
    content: >-
      [TestMethod]

      public void TestSetAndGetMaxX()
    content.vb: >-
      <TestMethod>

      Public Sub TestSetAndGetMaxX()
  overload: ASE_Assignment_Test.GlobalConfigTest.TestSetAndGetMaxX*
  attributes:
  - type: Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute
    ctor: Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute.#ctor
    arguments: []
- uid: ASE_Assignment_Test.GlobalConfigTest.TestSetAndGetMaxY
  commentId: M:ASE_Assignment_Test.GlobalConfigTest.TestSetAndGetMaxY
  id: TestSetAndGetMaxY
  parent: ASE_Assignment_Test.GlobalConfigTest
  langs:
  - csharp
  - vb
  name: TestSetAndGetMaxY()
  nameWithType: GlobalConfigTest.TestSetAndGetMaxY()
  fullName: ASE_Assignment_Test.GlobalConfigTest.TestSetAndGetMaxY()
  type: Method
  source:
    remote:
      path: ASE_Assignment_Test/GlobalConfigTest.cs
      branch: main
      repo: https://github.com/ASE-Classroom/ase-demo-assignment-Prapti-Acharya.git
    id: TestSetAndGetMaxY
    path: ASE_Assignment_Test/GlobalConfigTest.cs
    startLine: 44
  assemblies:
  - ASE_Assignment_Test
  namespace: ASE_Assignment_Test
  summary: Tests setting and getting the MaxY property of the GlobalConfig class.
  example: []
  syntax:
    content: >-
      [TestMethod]

      public void TestSetAndGetMaxY()
    content.vb: >-
      <TestMethod>

      Public Sub TestSetAndGetMaxY()
  overload: ASE_Assignment_Test.GlobalConfigTest.TestSetAndGetMaxY*
  attributes:
  - type: Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute
    ctor: Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute.#ctor
    arguments: []
- uid: ASE_Assignment_Test.GlobalConfigTest.TestSetAndGetIsFillEnabled
  commentId: M:ASE_Assignment_Test.GlobalConfigTest.TestSetAndGetIsFillEnabled
  id: TestSetAndGetIsFillEnabled
  parent: ASE_Assignment_Test.GlobalConfigTest
  langs:
  - csharp
  - vb
  name: TestSetAndGetIsFillEnabled()
  nameWithType: GlobalConfigTest.TestSetAndGetIsFillEnabled()
  fullName: ASE_Assignment_Test.GlobalConfigTest.TestSetAndGetIsFillEnabled()
  type: Method
  source:
    remote:
      path: ASE_Assignment_Test/GlobalConfigTest.cs
      branch: main
      repo: https://github.com/ASE-Classroom/ase-demo-assignment-Prapti-Acharya.git
    id: TestSetAndGetIsFillEnabled
    path: ASE_Assignment_Test/GlobalConfigTest.cs
    startLine: 60
  assemblies:
  - ASE_Assignment_Test
  namespace: ASE_Assignment_Test
  summary: Tests setting and getting the IsFillEnabled property of the GlobalConfig class.
  example: []
  syntax:
    content: >-
      [TestMethod]

      public void TestSetAndGetIsFillEnabled()
    content.vb: >-
      <TestMethod>

      Public Sub TestSetAndGetIsFillEnabled()
  overload: ASE_Assignment_Test.GlobalConfigTest.TestSetAndGetIsFillEnabled*
  attributes:
  - type: Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute
    ctor: Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute.#ctor
    arguments: []
- uid: ASE_Assignment_Test.GlobalConfigTest.TestSetAndGetPenSize
  commentId: M:ASE_Assignment_Test.GlobalConfigTest.TestSetAndGetPenSize
  id: TestSetAndGetPenSize
  parent: ASE_Assignment_Test.GlobalConfigTest
  langs:
  - csharp
  - vb
  name: TestSetAndGetPenSize()
  nameWithType: GlobalConfigTest.TestSetAndGetPenSize()
  fullName: ASE_Assignment_Test.GlobalConfigTest.TestSetAndGetPenSize()
  type: Method
  source:
    remote:
      path: ASE_Assignment_Test/GlobalConfigTest.cs
      branch: main
      repo: https://github.com/ASE-Classroom/ase-demo-assignment-Prapti-Acharya.git
    id: TestSetAndGetPenSize
    path: ASE_Assignment_Test/GlobalConfigTest.cs
    startLine: 76
  assemblies:
  - ASE_Assignment_Test
  namespace: ASE_Assignment_Test
  summary: Tests setting and getting the PenSize property of the GlobalConfig class.
  example: []
  syntax:
    content: >-
      [TestMethod]

      public void TestSetAndGetPenSize()
    content.vb: >-
      <TestMethod>

      Public Sub TestSetAndGetPenSize()
  overload: ASE_Assignment_Test.GlobalConfigTest.TestSetAndGetPenSize*
  attributes:
  - type: Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute
    ctor: Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute.#ctor
    arguments: []
references:
- uid: ASE_Assignment_Test
  commentId: N:ASE_Assignment_Test
  href: ASE_Assignment_Test.html
  name: ASE_Assignment_Test
  nameWithType: ASE_Assignment_Test
  fullName: ASE_Assignment_Test
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: ASE_Assignment_Prapti_Acharya_77356684.MyAppCanvas.MyCanvas
  commentId: T:ASE_Assignment_Prapti_Acharya_77356684.MyAppCanvas.MyCanvas
  parent: ASE_Assignment_Prapti_Acharya_77356684.MyAppCanvas
  href: ASE_Assignment_Prapti_Acharya_77356684.MyAppCanvas.MyCanvas.html
  name: MyCanvas
  nameWithType: MyCanvas
  fullName: ASE_Assignment_Prapti_Acharya_77356684.MyAppCanvas.MyCanvas
- uid: ASE_Assignment_Prapti_Acharya_77356684.MyAppCanvas
  commentId: N:ASE_Assignment_Prapti_Acharya_77356684.MyAppCanvas
  href: ASE_Assignment_Prapti_Acharya_77356684.html
  name: ASE_Assignment_Prapti_Acharya_77356684.MyAppCanvas
  nameWithType: ASE_Assignment_Prapti_Acharya_77356684.MyAppCanvas
  fullName: ASE_Assignment_Prapti_Acharya_77356684.MyAppCanvas
  spec.csharp:
  - uid: ASE_Assignment_Prapti_Acharya_77356684
    name: ASE_Assignment_Prapti_Acharya_77356684
    href: ASE_Assignment_Prapti_Acharya_77356684.html
  - name: .
  - uid: ASE_Assignment_Prapti_Acharya_77356684.MyAppCanvas
    name: MyAppCanvas
    href: ASE_Assignment_Prapti_Acharya_77356684.MyAppCanvas.html
  spec.vb:
  - uid: ASE_Assignment_Prapti_Acharya_77356684
    name: ASE_Assignment_Prapti_Acharya_77356684
    href: ASE_Assignment_Prapti_Acharya_77356684.html
  - name: .
  - uid: ASE_Assignment_Prapti_Acharya_77356684.MyAppCanvas
    name: MyAppCanvas
    href: ASE_Assignment_Prapti_Acharya_77356684.MyAppCanvas.html
- uid: ASE_Assignment_Test.GlobalConfigTest.TestSetAndGetMaxX*
  commentId: Overload:ASE_Assignment_Test.GlobalConfigTest.TestSetAndGetMaxX
  href: ASE_Assignment_Test.GlobalConfigTest.html#ASE_Assignment_Test_GlobalConfigTest_TestSetAndGetMaxX
  name: TestSetAndGetMaxX
  nameWithType: GlobalConfigTest.TestSetAndGetMaxX
  fullName: ASE_Assignment_Test.GlobalConfigTest.TestSetAndGetMaxX
- uid: ASE_Assignment_Test.GlobalConfigTest.TestSetAndGetMaxY*
  commentId: Overload:ASE_Assignment_Test.GlobalConfigTest.TestSetAndGetMaxY
  href: ASE_Assignment_Test.GlobalConfigTest.html#ASE_Assignment_Test_GlobalConfigTest_TestSetAndGetMaxY
  name: TestSetAndGetMaxY
  nameWithType: GlobalConfigTest.TestSetAndGetMaxY
  fullName: ASE_Assignment_Test.GlobalConfigTest.TestSetAndGetMaxY
- uid: ASE_Assignment_Test.GlobalConfigTest.TestSetAndGetIsFillEnabled*
  commentId: Overload:ASE_Assignment_Test.GlobalConfigTest.TestSetAndGetIsFillEnabled
  href: ASE_Assignment_Test.GlobalConfigTest.html#ASE_Assignment_Test_GlobalConfigTest_TestSetAndGetIsFillEnabled
  name: TestSetAndGetIsFillEnabled
  nameWithType: GlobalConfigTest.TestSetAndGetIsFillEnabled
  fullName: ASE_Assignment_Test.GlobalConfigTest.TestSetAndGetIsFillEnabled
- uid: ASE_Assignment_Test.GlobalConfigTest.TestSetAndGetPenSize*
  commentId: Overload:ASE_Assignment_Test.GlobalConfigTest.TestSetAndGetPenSize
  href: ASE_Assignment_Test.GlobalConfigTest.html#ASE_Assignment_Test_GlobalConfigTest_TestSetAndGetPenSize
  name: TestSetAndGetPenSize
  nameWithType: GlobalConfigTest.TestSetAndGetPenSize
  fullName: ASE_Assignment_Test.GlobalConfigTest.TestSetAndGetPenSize
